// Generated by the Release-to-Pages workflow; the browser needs no GitHub token.
export const firmwareSource = {
  type: "release",
  owner: "446599",
  repo: "whiteos",
  indexPath: "../firmware/releases.json",
};
